Divya hr
rambabu/employee-managemnet pull request #3
Opened 2023-05-03 23:41 UTC by Samrudhsaish

Hi, I am working on Human Management Resource module.

2023-05-04 02:36 UTC, rambabu requested changes

2023-05-04 02:36 UTC, rambabu commented on .idea/.gitignore
add a gitignore file

2023-05-04 02:36 UTC, rambabu commented on src/com/acro/emp/hrmodule/HR.java
> +
I need props and methods

2023-05-09 00:35 UTC, Ranianirudh requested changes

2023-05-09 00:35 UTC, Ranianirudh commented on src/com/acro/emp/AddProject.java
> +        public static void main (String[]args){
main is not needed in all the classes.

2023-05-09 00:35 UTC, Ranianirudh commented on src/com/acro/emp/AddProject.java
> +public class AddProject extends ProjectDetails{
As for as I know, Inheritance is not required here.

2023-05-09 02:40 UTC, merged